#!/usr/bin/env python3
"""Generate thin LEA and private entity shells for static http.server."""
from __future__ import annotations

import csv
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CSV_PATH = ROOT / "districts.csv"

LEA_SHELL = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title} · AI Policy Map</title>
  <meta name="description" content="AI policy snapshot for {title}." />
  <link rel="stylesheet" href="/assets/app.css" />
</head>
<body data-page="lea">
  <div class="wrap">
    <header class="site-header">
      <a class="brand" href="/">
        <strong>AI Policy Map</strong>
        <span>For students and teachers</span>
      </a>
      <nav class="nav" aria-label="Primary">
        <a href="/">Find district</a>
        <a href="/ga/">Georgia</a>
        <a href="/compare/">Compare</a>
        <a href="/about/">About</a>
      </nav>
    </header>
    <main id="entity-root">
      <div class="card"><p class="lead">Loading {title}…</p></div>
    </main>
    <footer class="site-footer">
      <span><a href="/ga/">← Georgia LEAs</a></span>
      <span>slug: <code>{slug}</code></span>
    </footer>
  </div>
  <script src="/assets/csv.js"></script>
  <script src="/assets/slug-map.js"></script>
  <script src="/assets/app.js"></script>
</body>
</html>
"""

PRIVATE_SHELL = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title} · AI Policy Map</title>
  <meta name="description" content="AI policy snapshot for {title} (private)." />
  <link rel="stylesheet" href="/assets/app.css" />
</head>
<body data-page="private">
  <div class="wrap">
    <header class="site-header">
      <a class="brand" href="/">
        <strong>AI Policy Map</strong>
        <span>For students and teachers</span>
      </a>
      <nav class="nav" aria-label="Primary">
        <a href="/">Find district</a>
        <a href="/ga/">Georgia</a>
        <a href="/compare/">Compare</a>
        <a href="/about/">About</a>
      </nav>
    </header>
    <main id="entity-root">
      <div class="card"><p class="lead">Loading {title}…</p></div>
    </main>
    <footer class="site-footer">
      <span><a href="/">← Find district</a></span>
      <span>slug: <code>{slug}</code></span>
    </footer>
  </div>
  <script src="/assets/csv.js"></script>
  <script src="/assets/slug-map.js"></script>
  <script src="/assets/app.js"></script>
</body>
</html>
"""


def slugify(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", name.lower())
    s = re.sub(r"-+", "-", s).strip("-")
    return s


def html_escape(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def main() -> None:
    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    lea_dir = ROOT / "lea"
    priv_dir = ROOT / "private"
    lea_dir.mkdir(parents=True, exist_ok=True)
    priv_dir.mkdir(parents=True, exist_ok=True)

    lea_count = 0
    priv_count = 0
    slug_map = []

    for row in rows:
        name = (row.get("district") or "").strip()
        if not name:
            continue
        slug = slugify(name)
        et = (row.get("entity_type") or "").strip()
        state = (row.get("state") or "").strip()

        if state == "GA" and et in ("traditional", "charter"):
            out = lea_dir / slug / "index.html"
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(
                LEA_SHELL.format(title=html_escape(name), slug=html_escape(slug)),
                encoding="utf-8",
            )
            lea_count += 1
            slug_map.append({"slug": slug, "district": name, "path": f"/lea/{slug}/", "entity_type": et})
        elif et == "private":
            out = priv_dir / slug / "index.html"
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(
                PRIVATE_SHELL.format(title=html_escape(name), slug=html_escape(slug)),
                encoding="utf-8",
            )
            priv_count += 1
            slug_map.append({"slug": slug, "district": name, "path": f"/private/{slug}/", "entity_type": et})

    # Small JS slug map for hydration reliability / tooling
    assets = ROOT / "assets"
    assets.mkdir(parents=True, exist_ok=True)
    lines = ["/* Auto-generated by build_pages.py — do not edit */", "window.AIPM_BUILD_SLUGS = {"]
    for item in slug_map:
        d = item["district"].replace("\\", "\\\\").replace("'", "\\'")
        lines.append(
            f"  '{item['slug']}': {{ district: '{d}', path: '{item['path']}', entity_type: '{item['entity_type']}' }},"
        )
    lines.append("};")
    lines.append("")
    (assets / "slug-map.js").write_text("\n".join(lines), encoding="utf-8")

    print(f"Generated {lea_count} LEA pages under lea/")
    print(f"Generated {priv_count} private pages under private/")
    print(f"Wrote assets/slug-map.js ({len(slug_map)} entries)")


if __name__ == "__main__":
    main()
